name: Synopsis Scan SCA (Schedule)
on:
  schedule:
    - cron:  '0 14 * * *' # Runs midnight (UTC) every day
jobs:
  synopsis-scan-sca:
    uses: compono/reusable-workflows/.github/workflows/synopsis-scan-sca.yml@main
    with:
      BLACKDUCK_URL: https://compono.app.blackduck.com
      PROJECT_NAME: ${{ github.event.repository.name }}
      APPLICATION_NAME: shared-services
      SCAN_TYPE: INTELLIGENT
    secrets:
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
