name: Test
on: push
env:
  MONGO_VERSION: 6.0.19
jobs:
  run-test:
    name: Run test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      issues: read
      pull-requests: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::468203661337:role/deploy # deploy@shared-services-prod
          role-session-name: publish-package-to-aws-codeartifact
          role-duration-seconds: 900

      - name: Set AWS CodeArtifact Token
        # https://docs.aws.amazon.com/codeartifact/latest/ug/npm-auth.html#configure-npm-login-command
        run: |
          aws codeartifact login --tool npm --namespace @do_not_override_global --repository shortlyster --domain compono --domain-owner 468203661337 --region ap-southeast-2

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: npm ci

      - name: Run test
        run: make test

      - name: Build packages
        run: npm run build
